Repository Chatterino/chatterino2, pull requests merged in 2021-08, with the labels that each got.

#3078 Deprecated /(un)follow commands and respective usercard action
  CHANGELOG.md
  src/controllers/commands/CommandController.cpp
  src/providers/twitch/TwitchAccount.cpp
  src/providers/twitch/TwitchAccount.hpp
  src/providers/twitch/api/Helix.cpp
  src/providers/twitch/api/Helix.hpp
  src/providers/twitch/api/README.md
  src/widgets/dialogs/UserInfoPopup.cpp
  src/widgets/dialogs/UserInfoPopup.hpp
Labels: twitch

#3122 Fix QJsonArray assert failing while attempting to index an empty array
  src/providers/twitch/api/Helix.cpp
Labels: no changelog entry needed

#3145 Added links to discussions when trying to create an issue
  .github/ISSUE_TEMPLATE/config.yml
Labels: no changelog entry needed

#3103 Prepare CMake for Qt6
  CHANGELOG.md
  CMakeLists.txt
  src/CMakeLists.txt
Labels: no changelog entry needed

#3038 Add basic benchmark
  CHANGELOG.md
  CMakeLists.txt
  benchmarks/.clang-format
  benchmarks/CMakeLists.txt
  benchmarks/src/Emojis.cpp
  benchmarks/src/main.cpp
  docs/test-and-benchmark.md
  tests/CMakeLists.txt
Labels: no changelog entry needed

#3158 Change 3rd party uploader popup text capitalization
  src/widgets/splits/Split.cpp
Labels: no changelog entry needed

#2800 Rewrite logic for when to show moderation buttons next to messages
  src/providers/twitch/TwitchMessageBuilder.cpp
  src/providers/twitch/TwitchMessageBuilder.hpp
Labels: no changelog entry needed

#3169 Keyboard integration for Streamlink quality confirmation
  src/util/StreamLink.cpp
  src/widgets/BasePopup.cpp
  src/widgets/BasePopup.hpp
  src/widgets/dialogs/QualityPopup.cpp
  src/widgets/dialogs/QualityPopup.hpp
Labels: no changelog entry needed

#3171 Make the browser extension issue template properly redirect
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/z_browser_extension.md
Labels: no changelog entry needed

#3180 Update Usage messages to conform to new Usage message contributor guidelines
  CONTRIBUTING.md
  src/controllers/commands/CommandController.cpp
  src/providers/twitch/IrcMessageHandler.cpp
Labels: no changelog entry needed

#3190 Fixed away command in IRC
  src/providers/irc/IrcCommands.cpp
Labels: irc, no changelog entry needed

#3188 Normalize usages of 'case-sensitive'
  src/widgets/settingspages/IgnoresPage.cpp
  src/widgets/settingspages/NicknamesPage.cpp
Labels: no changelog entry needed
