Repository Chatterino/chatterino2, pull requests merged in 2021-07, with the labels that each got.

#2948 Fix logging category names
  src/common/QLogging.cpp
Labels: no changelog entry needed

#2950 fix overflows in the max image size code
  src/messages/Image.cpp
Labels: no changelog entry needed

#2945 Replace QRegExp with QRegularExpression
  src/common/Args.cpp
  src/util/NuulsUploader.cpp
Labels: no changelog entry needed

#2966 Fix text mistakes in advanced login dialog
  src/widgets/dialogs/LoginDialog.cpp
Labels: no changelog entry needed

#2975 Add Talen to contributors
  resources/contributors.txt
Labels: no changelog entry needed

#2974 Moved getRandomColor method to util/Helpers.cpp
  src/messages/SharedMessageBuilder.cpp
  src/providers/twitch/TwitchMessageBuilder.cpp
  src/util/Helpers.cpp
  src/util/Helpers.hpp
Labels: no changelog entry needed

#2976 Set proper minimum width of name display modes dropdown
  src/widgets/settingspages/GeneralPage.cpp
Labels: no changelog entry needed

#2990 Added SLCH to contributors list
  resources/avatars/slch.png
  resources/contributors.txt
  resources/resources_autogenerated.qrc
  src/autogenerated/ResourcesAutogen.cpp
  src/autogenerated/ResourcesAutogen.hpp
Labels: no changelog entry needed

#3017 Remove unused class JsonQuery
  chatterino.pro
  src/CMakeLists.txt
  src/util/JsonQuery.cpp
  src/util/JsonQuery.hpp
Labels: no changelog entry needed

#3021 Cleaned up IrcMessageHandler
  src/common/Channel.hpp
  src/providers/twitch/IrcMessageHandler.cpp
  src/providers/twitch/TwitchChannel.hpp
  src/providers/twitch/TwitchIrcServer.cpp
Labels: no changelog entry needed

#3026 Use server time in received IRC messages where available
  CHANGELOG.md
  src/providers/irc/IrcMessageBuilder.cpp
  src/providers/irc/IrcServer.cpp
  src/util/IrcHelpers.hpp
Labels: irc

#3015 Cleanup debug logging
  src/messages/layouts/MessageLayoutElement.cpp
  src/providers/twitch/PubsubClient.cpp
Labels: no changelog entry needed

#3036 Add tests for `getEmoteSetBatches`
  src/providers/twitch/TwitchAccount.cpp
  src/providers/twitch/TwitchAccount.hpp
  tests/CMakeLists.txt
  tests/src/TwitchAccount.cpp
Labels: no changelog entry needed

#3018 Replace std::string with QString in rapidjson and PubSub Client
  src/providers/twitch/PubsubClient.cpp
  src/providers/twitch/PubsubClient.hpp
  src/util/RapidjsonHelpers.cpp
  src/util/RapidjsonHelpers.hpp
Labels: no changelog entry needed, pubsub

#3039 Make use of QUrlQuery in NetworkRequests where it was hardcoded into url
  src/providers/twitch/TwitchBadges.cpp
  src/providers/twitch/TwitchChannel.cpp
Labels: no changelog entry needed

#3067 Overengineered helper function to format a user mention
  src/common/CompletionModel.cpp
  src/util/Helpers.cpp
  src/util/Helpers.hpp
  src/widgets/helper/ChannelView.cpp
  src/widgets/splits/SplitInput.cpp
  tests/CMakeLists.txt
  tests/src/Helpers.cpp
Labels: no changelog entry needed

#3056 Remove copyDarkTheme.png which was an unused SVG file.
  resources/buttons/copyDarkTheme.png
  resources/resources_autogenerated.qrc
  src/autogenerated/ResourcesAutogen.cpp
  src/autogenerated/ResourcesAutogen.hpp
Labels: no changelog entry needed

#3048 ⬆️ Updated conan dependencies
  conanfile.txt
Labels: no changelog entry needed

#3042 Fix non secure wiki link
  src/widgets/settingspages/ModerationPage.cpp
Labels: no changelog entry needed

#3090 Pin down libcommuni's branch we're using
  .gitmodules
Labels: no changelog entry needed

#3093 Removed checks for no longer supported Qt 5.11
  src/widgets/BaseWindow.cpp
  src/widgets/FramelessEmbedWindow.cpp
Labels: no changelog entry needed

#3072 Adding xHeaveny to Contributor List
  resources/avatars/xheaveny.png
  resources/contributors.txt
  resources/resources_autogenerated.qrc
  src/autogenerated/ResourcesAutogen.cpp
  src/autogenerated/ResourcesAutogen.hpp
Labels: no changelog entry needed

#3097 Add ALazyMeme to the contributor list
  resources/avatars/alazymeme.png
  resources/contributors.txt
  resources/resources_autogenerated.qrc
  src/autogenerated/ResourcesAutogen.cpp
  src/autogenerated/ResourcesAutogen.hpp
Labels: no changelog entry needed
