Repository Chatterino/chatterino2, pull requests merged in 2022-10, with the labels that each got.

#4018 Add `is:elevated-msg` search predicate
  CHANGELOG.md
  src/messages/search/MessageFlagsPredicate.cpp
Labels: hacktoberfest-accepted

#4028 fix: `smoothScrollingNewMessages` sometimes hiding messages
  CHANGELOG.md
  src/widgets/Scrollbar.cpp
Labels: hacktoberfest-accepted

#4025 Migrate /unvip to Helix API
  CHANGELOG.md
  src/controllers/commands/CommandController.cpp
  src/providers/twitch/api/Helix.cpp
  src/providers/twitch/api/Helix.hpp
  tests/src/HighlightController.cpp
Labels: hacktoberfest-accepted

#4033 fix: set `gtest_force_shared_crt` in tests
  CMakeLists.txt
Labels: no changelog entry needed

#4029 Migrate `/raid` to Helix.
  CHANGELOG.md
  src/common/QLogging.cpp
  src/common/QLogging.hpp
  src/controllers/commands/CommandController.cpp
  src/providers/twitch/api/Helix.cpp
  src/providers/twitch/api/Helix.hpp
  src/singletons/Settings.hpp
  src/widgets/settingspages/GeneralPage.cpp
  tests/src/HighlightController.cpp
Labels: hacktoberfest-accepted

#4015 Migrate /emoteonly and /emoteonlyoff commands to the Helix API
  CHANGELOG.md
  src/controllers/commands/CommandController.cpp
  src/providers/twitch/api/Helix.cpp
  src/providers/twitch/api/Helix.hpp
  src/widgets/splits/SplitHeader.cpp
  tests/src/HighlightController.cpp
Labels: hacktoberfest-accepted

#4037 Add debug hotkey for test sub messages
  src/controllers/hotkeys/ActionNames.hpp
  src/widgets/Window.cpp
Labels: no changelog entry needed

#4040 Migrate Remaining Chat Settings Commands to Helix API
  CHANGELOG.md
  src/controllers/commands/CommandController.cpp
  src/providers/twitch/api/Helix.cpp
  src/providers/twitch/api/Helix.hpp
  src/util/Helpers.cpp
  src/util/Helpers.hpp
  tests/src/Helpers.cpp
Labels: hacktoberfest-accepted

#4042 Bump MessageFlag underlying type to be 64-bit
  src/common/Channel.hpp
  src/messages/Message.hpp
  src/messages/layouts/MessageLayoutContainer.hpp
  src/widgets/helper/ChannelView.hpp
Labels: no changelog entry needed

#4030 Migrate `/unraid` to Helix.
  CHANGELOG.md
  src/controllers/commands/CommandController.cpp
  src/providers/twitch/api/Helix.cpp
  src/providers/twitch/api/Helix.hpp
  tests/src/HighlightController.cpp
Labels: hacktoberfest-accepted

#4058 Fix FreeBSD Cirrus CI build
  .cirrus.yml
Labels: no changelog entry needed

#4059 Swap back to main branch of ZedThree's clang-tidy-review
  .github/workflows/build.yml
  .github/workflows/post-clang-tidy-review.yml
Labels: no changelog entry needed

#4061 Update 1xelerate contributors github link
  resources/contributors.txt
Labels: no changelog entry needed

#4066 Prevent copying in a couple places
  src/controllers/filters/parser/FilterParser.cpp
  src/widgets/helper/ResizingTextEdit.cpp
  src/widgets/settingspages/ModerationPage.cpp
Labels: no changelog entry needed, hacktoberfest-accepted

#4070 Migrated `getSubage` to v2 version of the API
  src/providers/IvrApi.cpp
  src/providers/IvrApi.hpp
Labels: no changelog entry needed

#4081 Remove unused values from MessageLayoutContainer
  .clang-tidy
  src/messages/layouts/MessageLayoutContainer.hpp
Labels: no changelog entry needed

#4085 Copied and adjusted BUILDING_ON_LINUX.md from SevenTV
  BUILDING_ON_LINUX.md
Labels: no changelog entry needed

#4086 Update IRC whisper error
  src/providers/twitch/IrcMessageHandler.cpp
Labels: no changelog entry needed

#4087 feat: Basic PubSub Manager for Live Emote Updates
  .clang-tidy
  .github/workflows/test.yml
  src/CMakeLists.txt
  src/common/QLogging.cpp
  src/common/QLogging.hpp
  src/providers/liveupdates/BasicPubSubClient.hpp
  src/providers/liveupdates/BasicPubSubManager.hpp
  src/providers/liveupdates/BasicPubSubWebsocket.hpp
  tests/CMakeLists.txt
  tests/src/BasicPubSub.cpp
Labels: no changelog entry needed

#4091 Add helper function for ensuring a function is run in the GUI thread
  src/messages/Image.cpp
  src/util/PostToThread.hpp
Labels: no changelog entry needed

#4092 Add missing Text tag to reply message text
  src/providers/twitch/TwitchMessageBuilder.cpp
Labels: no changelog entry needed

#4093 Grammar: Alias to -> Alias of
  src/providers/seventv/SeventvEmotes.cpp
Labels: no changelog entry needed
