Repository Chatterino/chatterino2, pull requests merged in 2022-05, with the labels that each got.

#3713 fix: raise existing emote popups from behind other windows (macOS)
  CHANGELOG.md
  src/widgets/splits/SplitInput.cpp
Labels: mac

#3714 Disable formatting on "contested lines"
  src/messages/MessageBuilder.hpp
  src/util/LayoutCreator.hpp
Labels: no changelog entry needed

#3724 Add missing vector header
  src/controllers/hotkeys/Hotkey.hpp
Labels: no changelog entry needed

#3725 Add missing QDebug header
  src/providers/twitch/PubSubActions.hpp
Labels: no changelog entry needed

#3727 Added `/debug-env` command
  src/controllers/commands/CommandController.cpp
Labels: no changelog entry needed

#3726 Fix `Qt::SkipEmptyParts` deprecation warning
  src/controllers/commands/CommandController.cpp
  src/messages/search/AuthorPredicate.cpp
  src/messages/search/ChannelPredicate.cpp
  src/messages/search/LinkPredicate.cpp
  src/messages/search/MessageFlagsPredicate.cpp
  src/util/Qt.hpp
  src/widgets/settingspages/CommandPage.cpp
Labels: no changelog entry needed

#3735 Store serverReceivedTime in messages
  src/messages/Message.hpp
  src/providers/irc/IrcMessageBuilder.cpp
  src/providers/irc/IrcServer.cpp
  src/providers/twitch/IrcMessageHandler.cpp
  src/providers/twitch/TwitchMessageBuilder.cpp
  src/util/IrcHelpers.hpp
Labels: no changelog entry needed

#3634 Add guide for building chatterino2 on Windows with vcpkg
  .gitignore
  BUILDING_ON_WINDOWS_WITH_VCPKG.md
  CMakeLists.txt
  README.md
  src/CMakeLists.txt
  tests/CMakeLists.txt
  vcpkg.json
Labels: no changelog entry needed

#3743 Remove unused Env member for emoteset resolver url
  src/common/Env.cpp
  src/common/Env.hpp
  src/controllers/commands/CommandController.cpp
Labels: no changelog entry needed

#3741 fix: compilation on macOS without precompiled headers
  src/providers/ffz/FfzBadges.hpp
  src/widgets/splits/SplitContainer.hpp
Labels: no changelog entry needed

#3744 Removed unused `refreshButton` pointer
  src/widgets/dialogs/UserInfoPopup.hpp
Labels: no changelog entry needed

#3748 ci: cancel previous runs on PR update
  .github/workflows/build.yml
  .github/workflows/check-formatting.yml
  .github/workflows/lint.yml
  .github/workflows/push-aur.yml
  .github/workflows/test.yml
Labels: ci

#3753 Fix vcpkg manifest and finding RapidJSON and Websocketpp modules
  cmake/FindRapidJSON.cmake
  cmake/FindWebsocketpp.cmake
  vcpkg.json
Labels: no changelog entry needed

#3749 Updated link to VCRedist in README
  README.md
Labels: windows, no changelog entry needed

#3756 Make Helix an interface
  src/providers/twitch/api/Helix.cpp
  src/providers/twitch/api/Helix.hpp
Labels: no changelog entry needed

#3758 Make an IApplication interface
  src/Application.cpp
  src/Application.hpp
Labels: no changelog entry needed

#3759 Add Visual Studio stuff to .gitignore
  .gitignore
Labels: no changelog entry needed

#3751 Automatically place newlines at end of generated files
  resources/_generate_resources.py
Labels: no changelog entry needed

#3390 update to vs 2022 on building file
  BUILDING_ON_WINDOWS.md
Labels: no changelog entry needed

#3771 Corrected the way we parse comma-separated "list tags" in PRIVMSGs
  src/controllers/highlights/HighlightBadge.cpp
  src/messages/Message.hpp
  src/messages/SharedMessageBuilder.cpp
  src/messages/SharedMessageBuilder.hpp
  src/providers/twitch/TwitchBadge.cpp
  src/providers/twitch/TwitchBadge.hpp
  src/providers/twitch/TwitchMessageBuilder.cpp
  src/providers/twitch/TwitchMessageBuilder.hpp
  tests/CMakeLists.txt
  tests/src/TwitchMessageBuilder.cpp
Labels: no changelog entry needed

#3736 Add safe checks around use of QImageReader
  src/messages/Image.cpp
  src/messages/MessageBuilder.cpp
  src/providers/twitch/TwitchBadges.cpp
Labels: no changelog entry needed

#3776 Removed unused files IsBigEndian.hpp and rangealgorithm.hpp
  chatterino.pro
  src/Application.cpp
  src/BrowserExtension.cpp
  src/util/IsBigEndian.hpp
  src/util/rangealgorithm.hpp
Labels: no changelog entry needed

#3777 Optimize formatTime utility
  benchmarks/CMakeLists.txt
  benchmarks/src/FormatTime.cpp
  src/util/FormatTime.cpp
  tests/CMakeLists.txt
  tests/src/FormatTime.cpp
Labels: no changelog entry needed

#3775 Simplify code for fake debug messages
  chatterino.pro
  src/CMakeLists.txt
  src/util/DebugCount.hpp
  src/util/SampleCheerMessages.hpp
  src/util/SampleData.cpp
  src/util/SampleData.hpp
  src/util/SampleLinks.hpp
  src/widgets/Window.cpp
Labels: no changelog entry needed

#3778 Run httpbin docker image locally in CI
  .github/workflows/test.yml
  tests/README.md
  tests/src/NetworkRequest.cpp
Labels: no changelog entry needed

#3785 Use `setPlainText` when finishing a completion
  src/widgets/splits/SplitInput.cpp
Labels: no changelog entry needed
