Repository Chatterino/chatterino2, pull requests merged in 2024-04, with the labels that each got.

#5312 add nealxm to contributors list
  resources/avatars/nealxm.png
  resources/contributors.txt
Labels: no changelog entry needed

#5337 Release v2.5.0
  CHANGELOG.md
  resources/com.chatterino.chatterino.appdata.xml
  src/common/Version.hpp
Labels: skip-changelog-checker

#5346 refactor: clean up toStdString usages in tests
  tests/src/Emojis.cpp
  tests/src/LinkParser.cpp
  tests/src/TestHelpers.hpp
  tests/src/TwitchMessageBuilder.cpp
  tests/src/XDGHelper.cpp
Labels: no changelog entry needed

#5347 fix: warning in homebrew workflow
  .github/workflows/homebrew.yml
Labels: no changelog entry needed

#5365 ci: add workflow for WinGet
  .github/workflows/winget.yml
Labels: ci

#5368 docs: fix typo
  tests/README.md
Labels: no changelog entry needed
