Repository Chatterino/chatterino2, pull requests merged in 2025-01, with the labels that each got.

#5791 Release v2.5.2
  CHANGELOG.md
  CMakeLists.txt
  resources/com.chatterino.chatterino.appdata.xml
  src/common/Version.hpp
Labels: no changelog entry needed, skip-changelog-checker

#5793 chore: bump winget-releaser action
  .github/workflows/winget.yml
Labels: ci

#5813 fix: update winget repo url
  .github/workflows/winget.yml
Labels: ci

#5814 fix: winget url fix
  .github/workflows/winget.yml
Labels: ci

#5835 chore(ci): build & test macos with Boost 1.87
  .github/workflows/build.yml
  .github/workflows/test-macos.yml
Labels: ci

#5792 Update chatterino.d.ts to match plugin-meta.lua
  .prettierrc
  docs/chatterino.d.ts
  docs/plugin-meta.lua
  src/providers/twitch/TwitchChannel.hpp
Labels: no changelog entry needed

#5839 chore(tests): print more errors when snapshot tests fail
  tests/src/IrcMessageHandler.cpp
Labels: ci

#5840 chore(tests): don't use variants 😠
  tests/src/IrcMessageHandler.cpp
Labels: ci

#5864 docs: update linux & test docs
  BUILDING_ON_LINUX.md
  tests/README.md
Labels: no changelog entry needed

#5877 chore(ci): bump twitch pubsub server version to v1.0.8
  .github/workflows/test-macos.yml
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
Labels: ci
